### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by darkdarcool** [darkdarcool/DarkCSS#1]
People are needed to help with the development of DarkCSS! The second project in my 100 cycle special!

But, I need help.

This is going to be a big project, and I'll need a lot of help.

So, if you know JS, I would ❤️ to have you on the team!

Bai!

**Comment by iop3** [comment]
> So, if you know JS, I would ❤️ to have you on the team!

simply do this @darkdarcool: (~~PING RAYHANADEV~~) @RayhanAdev

**Comment by darkdarcool** [comment]
uh, ok, I don't wanna ping, but ok?

**Comment by iop3** [comment]
xD

**Comment by iop3** [comment]
oh wow! first time u replied so fast..

**Comment by darkdarcool** [comment]
I’m on my phone, and I was watching YouTube:)

**Comment by iop3** [comment]
oh! 

(watching what?)

**Comment by darkdarcool** [comment]
https://m.youtube.com/watch?v=DTvS9lvRxZ8

**Comment by iop3** [comment]
rip youtube is blocked for me just tell me what the name of the video is

**Comment by RayhanADev** [comment]
> oh! js right? simply do this @darkdarcool: (PING RAYHANADEV) @RayhanADev
@iop3 lmfao

@darkdarcool I would help but I don't want to commit myself and not be able to actually do work. In like one week my school ends and summer vacation starts so I'll check my schedule and see if I can help out :)

**Comment by darkdarcool** [comment]
k cool. I'll tell you when I can work later today, ping me over here when you can

**Comment by iop3** [comment]
lucky @RayhanADev i still have like about 1 month of sChOoL left >:(

**Comment by darkdarcool** [comment]
lol I have 2 or 4 more days

**Comment by iop3** [comment]
:O, >:(

**Comment by darkdarcool** [comment]
@RayhanADev, I invited you, you can work whenever, If you can try to tell me when you're on :)
